### ISSUE TITLE
Go to a specific frame

### ISSUE THREAD

**Issue by Gorusss** [Pixofield/keyshapejs#1]
Hello

The first thing to say is that I love Keyshape and say that its simplicity is making it very popular in our agency. Great job.

Now. I'm used to working with Lottie. And it has the ability to access a specific frame of an animation. This way you can have different phases of an animation in just one file.

Keyshape JS allows you to do something similar?

**Comment by Pixofield** [comment]
Keyshape outputs animations as a timeline. You can go to a specific time like this (the time is milliseconds):

    let tl = KeyshapeJS.timelines()[0];  // access the timeline
    tl.time(1000);     // set the time

You can control the playback of the timeline like this:

    tl.play();
    tl.pause();

You can set a play range for a timeline like this (a bit like Lottie's segments) and play it from the start of the range. It will automatically stop at the end of the range.

    tl.range(1000, 2000);
    tl.play(1000)

The play range can be dynamically changed to play other parts of the timeline.

The Keyshape support page has a tutorial showing how to play different parts of an animation: https://www.keyshapeapp.com/tutorials/onboarding-animation-with-keyshapejs

**Comment by d-korolkov** [comment]
Plan to buy Keyshape after trial, but time in **milli**seconds... sounds odd when you're creating the animation. 30fps, 60fps - this is standard I guess, and changing between time \ frame timelines

**Comment by Pixofield** [comment]
You can convert from frames to milliseconds like this:

    let frameNumber = 320;
    let fps = 60;
    let timeMs = frameNumber / fps;

`frameNumber` is the frame number you want to go to, `fps` is the frame rate for the animation and `timeMs` is the time in millisecs. Then, just use the time() function to jump to the time: `tl.time(timeMs);`

You can also use time markers instead of hardcoded absolute times.
