### ISSUE TITLE
triggers for timeline events

### ISSUE THREAD

**Issue by pixelpaulaus** [Pixofield/keyshapejs#8]
Hello,
I am liking keyshapejs a lot so far.
My only question before i use it is...
Is it possible to have events/trigger during the timeline.
So if the timeline reaches a certain time, there will be a trigger of some code which can then control the timeline.

Example: If the timeline reaches 500, it will run some code to check something and either return back to 0 on the timeline or continue.

**Comment by Pixofield** [comment]
There's no way to have events/trigger during the timeline.

You could use KeyshapeJS to play a certain range and get the onfinish callback called once the range has ended:

    KeyshapeJS.timelines()[0].onfinish = function() { console.log("range finished") };
    KeyshapeJS.timelines()[0].range(0, 500);
    KeyshapeJS.timelines()[0].play();

Is the goal to play a range in a loop and smoothly continue to the next range if some condition occurs?

One option is to use Lottie, which has a bit better API for these kind of animations.

**Comment by pixelpaulaus** [comment]
i have done the callback way, thanks for that.
